// Generate the app shell's runtime config from shell.config.json.
//
// One file owns the allow list. Capacitor reads it for `allowNavigation`, and
// the entry screen reads the generated www/config.js for its own validation.
// If those two ever disagreed, the app would offer a destination the WebView
// then refused to open, and the member would be handed to the system browser
// in the middle of registering.
//
// It REFUSES rather than warns. A shell built with a bad allow list is an app
// that either cannot navigate at all or can navigate anywhere, and both fail
// in a shop rather than here.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const MOBILE = join(HERE, '..', '..', 'apps', 'mobile');

/** A host is a bare hostname: no scheme, no path, no port, no wildcard-only. */
const HOST = /^(\*\.)?[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/i;

/**
 * Check a shell config, and say precisely what is wrong with it.
 *
 * Exported so the test suite can check the rules without writing files.
 *
 * @returns {string[]} problems; empty means the config is usable.
 */
export function validateShellConfig(config) {
  const problems = [];
  const hosts = config?.allowedHosts;

  if (!Array.isArray(hosts) || hosts.length === 0) {
    problems.push(
      'allowedHosts is empty. The app would be able to navigate nowhere. ' +
        'Put the real Yoyo Gyms address in apps/mobile/shell.config.json first.'
    );
  } else {
    for (const host of hosts) {
      if (typeof host !== 'string' || !HOST.test(host)) {
        problems.push(`"${host}" is not a bare hostname. Use "yoyogyms.com", not a URL or a path.`);
      }
      if (host === '*') {
        problems.push('"*" allows the WebView to follow any link anywhere, inside the app chrome.');
      }
    }
  }

  const server = config?.defaultServer;
  if (!server || typeof server !== 'string') {
    problems.push('defaultServer is empty. The app would open to a blank screen.');
  } else if (!server.startsWith('https://')) {
    // A member types their ID number and phone number into these screens, and
    // a gym's wi-fi is not a trusted network.
    problems.push(`defaultServer must be https://, got "${server}".`);
  } else {
    const host = new URL(server).hostname;
    if (Array.isArray(hosts) && !hosts.includes(host)) {
      problems.push(`defaultServer host "${host}" is not in allowedHosts — the app would open and immediately be blocked.`);
    }
  }

  // The one that matters most, and the reason adminHost is recorded at all.
  const admin = config?.adminHost;
  if (admin && Array.isArray(hosts) && hosts.includes(admin)) {
    problems.push(
      `adminHost "${admin}" is in allowedHosts. The staff admin panel must NOT be reachable ` +
        'from the member app — staff reach it in a browser. Remove it from allowedHosts.'
    );
  }

  return problems;
}

export function generate(config) {
  return `/* GENERATED by scripts/mobile/configure-shell.mjs from shell.config.json.
   Do not edit: \`npm run mobile:configure\` overwrites this file. */
window.YOYO_SHELL = Object.freeze({
  allowedHosts: Object.freeze(${JSON.stringify(config.allowedHosts)}),
  defaultServer: ${JSON.stringify(config.defaultServer)},
  supportContact: ${JSON.stringify(config.supportContact || '')},
});
`;
}

// Only run when invoked directly, so importing it in a test writes nothing.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const configPath = join(MOBILE, 'shell.config.json');
  const config = JSON.parse(readFileSync(configPath, 'utf8'));

  const problems = validateShellConfig(config);
  if (problems.length) {
    console.error('\nCannot configure the app shell:\n');
    for (const p of problems) console.error('  • ' + p);
    console.error(`\nEdit ${configPath} and run this again.\n`);
    process.exit(1);
  }

  mkdirSync(join(MOBILE, 'www'), { recursive: true });
  writeFileSync(join(MOBILE, 'www', 'config.js'), generate(config), 'utf8');
  console.log(`Wrote apps/mobile/www/config.js — ${config.allowedHosts.length} allowed host(s).`);
}
